# we are just doing this out of convenience while we explore
# the use of topics with Sarah.
# values for these keys represent a relative quantity of results found
# during exploration of the api.
# We have found that we can only do about 80 per call which is why I've
# commented out the last several while we decide which to use, or if we
# want to break the query up into several which we will collate before returning

_topics = {
    'Ageing': 1,
    'Agricultural and Biological Sciences(all)': 5,
    'Analytical Chemistry': 4,
    'Anesthesiology and Pain Medicine': 1,
    'Animal Science and Zoology': 2,
    'Applied Mathematics': 6,
    'Applied Microbiology and Biotechnology': 10,
    'Artificial Intelligence': 15,
    'Behavioral Neuroscience': 1,
    'Biochemistry': 25,
    'Biochemistry, Genetics and Molecular Biology(all)': 11,
    'Biochemistry, medical': 1,
    'Bioengineering': 18,
    'Biomedical Engineering': 12,
    'Biophysics': 8,
    'Biotechnology': 13,
    'Cancer Research': 282,
    'Cardiology and Cardiovascular Medicine': 17,
    'Cell Biology': 10,
    'Cellular and Molecular Neuroscience': 1,
    'Clinical Biochemistry': 8,
    'Clinical Neurology': 5,
    'Clinical Psychology': 5,
    'Cognitive Neuroscience': 7,
    'Complementary and alternative medicine': 1,
    'Computer Networks and Communications': 4,
    'Computer Science Applications': 13,
    'Computer Science(all)': 3,
    'Critical Care and Intensive Care Medicine': 6,
    'Dermatology': 1,
    'Developmental Biology': 4,
    'Drug Discovery': 7,
    'Ecological Modelling': 1,
    'Ecology': 3,
    'Ecology, Evolution, Behavior and Systematics': 3,
    'Economics and Econometrics': 4,
    'Emergency Medicine': 1,
    'Endocrinology': 6,
    'Endocrinology, Diabetes and Metabolism': 4,
    'Environmental Science(all)': 8,
    'Epidemiology': 2,
    'Experimental and Cognitive Psychology': 3,
    'Gastroenterology': 5,
    'General': 12,
    'Genetics': 22,
    'Genetics(clinical)': 1,
    'Health Informatics': 5,
    'Health Policy': 2,
    'Health(social science)': 2,
    'Health, Toxicology and Mutagenesis': 1,
    'Hematology': 23,
    'Histology': 1,
    'Human-Computer Interaction': 2,
    'Immunology': 4,
    'Immunology and Allergy': 4,
    'Immunology and Microbiology(all)': 1,
    'Infectious Diseases': 7,
    'Information Systems': 1,
    'Internal Medicine': 4,
    'Medicine (miscellaneous)': 3,
    'Medicine(all)': 60,
    'Microbiology (medical)': 2,
    'Molecular Biology': 28,
    'Molecular Medicine': 4,
    'Nephrology': 2,
    'Neuroscience(all)': 3,
    'Nutrition and Dietetics': 2,
    'Obstetrics and Gynaecology': 11,
    'Oncology': 305,
    'Oncology(nursing)': 1,
    'Ophthalmology': 1,
    'Oral Surgery': 2,
    'Organic Chemistry': 5,
    'Parasitology': 2,
    'Pathology and Forensic Medicine': 5,
    'Pediatrics, Perinatology, and Child Health': 5,
    'Pharmaceutical Science': 2,
    'Pharmacology': 7,
    'Pharmacology (medical)': 7,
    'Physical and Theoretical Chemistry': 37,
    'Physiology': 7,
    'Physiology (medical)': 8,
#    'Psychiatry and Mental health': 8,
#    'Psychology(all)': 2,
#    'Public Health, Environmental and Occupational Health': 13,
#    'Pulmonary and Respiratory Medicine': 22,
#    'Radiation': 2,
#    'Radiological and Ultrasound Technology': 5,
#    'Radiology Nuclear Medicine and imaging': 22,
#    'Reproductive Medicine': 1,
#    'Structural Biology': 1,
#    'Surgery': 31,
#    'Toxicology': 8,
#    'Transplantation': 3,
#    'Urology': 11,
#    'Virology': 1,

}
TOPICS = list(_topics.keys())

