"""
Django settings for rlp project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

gettext = lambda s: s

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'in settings.py'
USE_X_FORWARDED_HOST = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True

X_FRAME_OPTIONS = 'SAMEORIGIN'

PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
)

SITE_ID = 1

AUTH_USER_MODEL = 'accounts.User'

DEBUG = False

ALLOWED_HOSTS = [
    '.rapidscience.org',
]

# Application definition

INSTALLED_APPS = (
    'djangocms_admin_style',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.redirects',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'formtools',
    'localflavor',
    'rlp.accounts.apps.AccountsConfig',
    'actstream.apps.ActstreamConfig',
    'bootstrap3',
    'cms',
    'filer',
    'cmsplugin_filer_file',
    'cmsplugin_filer_folder',
    'cmsplugin_filer_image',
    'djangocms_blog',
    'djangocms_column',
    'djangocms_link',
    'djangocms_text_ckeditor',
    'django_comments',
    'el_pagination',
    'embed_video',
    'polymorphic',
    'treebeard',
    'mptt',
    'menus',
    'sekizai',
    'reversion',
    'aldryn_apphooks_config',
    'aldryn_search',
    'easy_thumbnails',
    'compressor',
    'haystack',
    'meta',
    'parler',
    'taggit',
    'taggit_autosuggest',
    'rlp.bibliography.apps.BibliographyConfig',
    'rlp.bookmarks.apps.BookmarksConfig',
    'rlp.core.apps.CoreConfig',
    'rlp.discussions',
    'rlp.documents.apps.DocumentsConfig',
    'rlp.events.apps.EventsConfig',
    'rlp.newsfeed.apps.NewsFeedConfig',
    'rlp.projects.apps.ProjectsConfig',
    'rlp.search.apps.SearchConfig',
    'django_extensions',
)

MIDDLEWARE_CLASSES = (
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
)

ROOT_URLCONF = 'rlp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'rlp', 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
                'rlp.core.context_processors.google_analytics',
                'rlp.core.context_processors.search_form',
            ],
        },
    },
]

LANGUAGES = (
    ('en-us', gettext('English')),
)

CMS_TEMPLATES = (
    ('home.html', 'Home Page'),
    ('cms/left_col.html', 'Content with left column'),
    ('cms/right_col.html', 'Content with right column'),
    ('projects/projects_list.html', 'Project Page'),
    ('newsfeed/newsfeed.html', 'News & Events'),
    ('cms/single_col.html', 'Full width content with no side columns'),
)

CMS_PLACEHOLDER_CONF = {
    'hero-text': {
        'plugins': ['TextPlugin'],
        'limits': {
            'TextPlugin': 1
        }
    },
    'hero-image': {
        'plugins': ['FilerImagePlugin'],
        'limits': {
            'FilerImagePlugin': 1
        }
    },
    'homepage-intro': {
        'plugins': ['TextPlugin'],
        'limits': {
            'TextPlugin': 1
        },
        'text_only_plugins': [
            'LinkPlugin',
            'FilerImagePlugin',
            'FilerFilePlugin',
        ]
    },
    'content': {
        'plugins': [
            'TextPlugin',
            'MultiColumnPlugin',
            'ProjectsPlugin'
        ],
        'text_only_plugins': [
            'LinkPlugin',
            'FilerImagePlugin',
            'FilerFilePlugin',
        ]
    },
    'bibliography': {
        'plugins': [
            'TextPlugin'
        ],
        'limits': {
            'TextPlugin': 1
        },
        'text_only_plugins': [
            'LinkPlugin',
            'FilerImagePlugin',
            'FilerFilePlugin',
        ]
    },
}

CMS_INTERNAL_IPS = []

WSGI_APPLICATION = 'rlp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'USER': 'web',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False

USE_L10N = True

USE_TZ = True

# Override these per site
REGISTRATION_REVIEWERS = []
REGISTRATION_REVIEWERS_FOR_APPROVAL_REQUIRED_PROJECTS = []

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# STATIC_URL = 'http://static.TBD.org/'
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# MEDIA_URL = 'http://media.TBD.org/'
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

COMPRESS_CSS_HASHING_METHOD = 'content'
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',
]

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)

THUMBNAIL_HIGH_RESOLUTION = True

GOOGLE_UA = ""

ORCID_CLIENT_ID = ''
ORCID_SECRET_KEY = ''

ZOTERO_URL = "in settings.py"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

ACTSTREAM_SETTINGS = {
    'MANAGER': 'actstream.managers.ActionManager',
    'FETCH_RELATIONS': False,
    'USE_JSONFIELD': False,
}

BOOTSTRAP3 ={
    'success_css_class': '',
    'set_placeholder': False,
    'required_css_class': 'required',
}

COMMENTS_APP = 'rlp.discussions'
COMMENTS_MAX_THREAD_LEVEL = 2
COMMENTS_MAX_THREAD_LEVEL_BY_APP_MODEL = {}
COMMENT_MAX_LENGTH = 3000


EL_PAGINATION_TEMPLATE_VARNAME = 'template_name'

EMBED_VIDEO_BACKENDS = [
    'embed_video.backends.YoutubeBackend',
    'embed_video.backends.VimeoBackend',
]

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'rlp.search.backends.ElasticsearchSearchEngine',
        'URL': 'http://127.0.0.1:9200/',
        'INDEX_NAME': 'haystack',
    },
}
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

INDEXABLE_EXTENSIONS = (
    'doc',
    'docx',
    'pdf',
    'ppt',
    'pptx',
    'rtf',
    'txt',
    'xls',
    'xlsx',
)

META_SITE_PROTOCOL = 'https'
META_USE_SITES = True

PUBMED_EMAIL = ''

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': os.path.join(BASE_DIR, 'log', 'rlp.log'),
        }
    },
    'loggers': {
        '': {
            'handlers': ['mail_admins', 'file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security.DisallowedHost': {
            'handlers': ['file'],
            'propagate': False,
        },
        'py.warnings': {
            'handlers': ['file'],
        }
    },
}
