# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments', '0002_update_user_email_field_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadedComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_comments.Comment')),
                ('thread_id', models.IntegerField(db_index=True, default=0)),
                ('parent_id', models.IntegerField(default=0)),
                ('level', models.SmallIntegerField(default=0)),
                ('order', models.IntegerField(db_index=True, default=1)),
            ],
            options={
                'ordering': ('-thread_id', 'order'),
            },
            bases=('django_comments.comment',),
        ),
    ]
