# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadedcomment',
            options={'ordering': ('-thread_id', 'order'), 'verbose_name': 'comment'},
        ),
    ]
