# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-27 15:15
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('managedtags', '0001_initial'),
        ('discussions', '0004_threadedcomment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadedcomment',
            name='mtags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='managedtags.TaggedByManagedTag', to='managedtags.ManagedTag', verbose_name='Tags'),
        ),
    ]
