# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-20 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_auto_20170630_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadedcomment',
            options={'ordering': ('thread_id', 'order'), 'verbose_name': 'comment'},
        ),
    ]
