# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-12-18 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0010_add_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadedcomment',
            name='origin_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='threadedcomment',
            name='origin_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
