# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160113_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
    ]
