# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160217_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
