# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160222_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tags_following',
        ),
    ]
