# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160420_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, help_text='If you do not have an ORCID ID, you can register for one <a href="https://orcid.org/register" target="_blank">here</a>', max_length=100, verbose_name='ORCID ID'),
        ),
    ]
