# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-22 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20160606_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(blank=True, max_length=255, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='state'),
        ),
    ]
