# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170412_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banner_photos'),
        ),
    ]
