# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-08 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_out_of_email',
            field=models.NullBooleanField(default=False),
        ),
    ]
