# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add__email__opt_out__to__user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='opt_out_of_email',
            field=models.BooleanField(default=False),
        ),
    ]
