# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-13 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_verbose_name_for_email_opt_outs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='opt_out_of_email',
        ),
        migrations.AddField(
            model_name='user',
            name='email_prefs',
            field=models.CharField(choices=[('immediate', 'Immediately notify me when an item is shared with         me or with a group to which I belong. Includes case reports,         documents, discussions, references and comments.'), ('digest', 'Send a weekly digest of all items shared with me or         with a group to which I belong.'), ('disabled', 'Do not send notification emails(*). I will check my         Dashboard to view shared items.')], default='digest', max_length=255, verbose_name='Email notification preferences'),
        ),
    ]
