# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-08-31 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180702_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_prefs',
            field=models.CharField(choices=[('user_and_group', 'Email me immediately when an item is shared with me individually or with groups to which I belong.'), ('user_only', 'Email me immediately only when an item is shared with me individually.'), ('disabled', 'Do not send immediate email notifications.*')], default='disabled', max_length=255, verbose_name='Email notification preferences'),
        ),
    ]
