# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-13 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('casereport', 'casefile', 'casefile_f'),
        migrations.RenameField('event', 'casereport', 'casereport_f'),
        migrations.RenameField('treatment', 'casereport', 'casereport_f'),
    ]
