# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-06 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0002_to_django_19'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casereport',
            name='history',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='index',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='molecular_abberations',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='other_sarcoma_type',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='precision_treatment',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='previous_treatments',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='progression',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='response',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='sarcoma_type',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='specimen_analyzed',
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='tumor_location',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_outcome',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='tumor_size',
        ),
        migrations.AddField(
            model_name='casereport',
            name='aberrations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casereport',
            name='biomarkers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casereport',
            name='presentation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casereport',
            name='subtype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_intent',
            field=models.CharField(blank=True, choices=[('Neoadjuvant', 'Neoadjuvant'), ('Adjuvant', 'Adjuvant'), ('Metastatic/Advanced', 'Metastatic/Advanced'), ('Palliative', 'Palliative')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='authorized_reps',
            field=models.ManyToManyField(blank=True, to='casereport.AuthorizedRep'),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='casefile_f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casereport.CaseFile', verbose_name='Case File'),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='referring_physician',
            field=models.ManyToManyField(blank=True, to='casereport.Physician'),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready to Review'), ('approved', 'Approved'), ('changes', 'Need Changes'), ('reviewed', 'Reviewed'), ('edited', 'Edited')], default='processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='casereport_f',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='casereport.CaseReport', verbose_name='Case Report'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('treatment', 'Treatment'), ('diagnosis', 'Diagnosis')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='casereport_f',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='casereport.CaseReport', verbose_name='Case Report'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='objective_response',
            field=models.CharField(blank=True, choices=[('No Response', 'No Response'), ('Partial Response', 'Partial Response'), ('Diseage Progression', 'Diseage Progression'), ('Complete Response', 'Complete Response')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
