# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-24 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0003_auto_20170306_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='attachment1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='casereport',
            name='attachment1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casereport',
            name='attachment1_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='casereport',
            name='attachment2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='casereport',
            name='attachment2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casereport',
            name='attachment2_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='casereport',
            name='attachment3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='casereport',
            name='attachment3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casereport',
            name='attachment3_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
