# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-24 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0004_auto_20170324_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='attachment1_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='attachment1_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='attachment2_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='attachment2_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='attachment3_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='attachment3_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
