# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0005_auto_20170324_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='attachment1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='attachment3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
