# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0006_auto_20170328_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='aberrations_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
