# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0007_casereport_aberrations_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('transgender_male', 'Transgender Male'), ('transgender_female', 'Transgender Female'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
