# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-07 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0009_auto_20170404_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='aberrations',
            field=models.CharField(blank=True, choices=[('38', 'X;18 SYT: translocation'), ('186', 'KRAS : amplification'), ('188', 'FGF23:  amplification'), ('190', 'FGF6:  amplification'), ('200', 'ERBB2: amplification'), ('201', 'APC:   R232 , A1283fs 5'), ('202', 'TP53 : splice site 97-1G&gt;A'), ('242', 'MDM2: Negative (FISH)'), ('243', 'FKHR:  Negative (FISH)'), ('252', 'PAX7: \xadNegative transcript (RT\xadPCR)'), ('271', 'PIK3CA : amplification'), ('272', 'FBXW7: splice site 1645-2A&gt;T'), ('273', 'FGFR2: amplificationEq'), ('274', 'JAK2: amplification'), ('275', 'MYC: amplificationEq'), ('276', 'SOX2: amplificationEq'), ('277', 'TP53: H179R'), ('278', 'BRCA1: S713*'), ('279', 'ATM: D1367fs 4   '), ('280', 'COL1A1-PDGFB: Fusion'), ('282', 'FGFR2: C382RSub'), ('283', 'ARID1A: G880fs 8'), ('284', 'CDKN2A: Loss'), ('285', 'MCL1: amplificationEq'), ('302', 'SS18: fusion transcripts'), ('303', '(SYT)-SSX: fusion '), ('305', ' t(X;18)(p11;q11): translocation'), ('361', 'TET2 T397fs*30 : Mutation'), ('383', 'aaa: erbb2'), ('389', 'COL1A1-PDGFB: : Positive (FISH)'), ('396', ': t(4;19)(q35;q13.1) CIC-DUX4 Fusion'), ('417', 'ALK-RANBP2: Translocation'), ('452', 'KIT exon 11: involving codons 557 and 558 '), ('499', 'ERBB2: '), ('581', 'CCND2: amplification'), ('598', ': '), ('617', 'dfghjk: dfghjk'), ('628', 'rrer: fghj'), ('638', 'COL1A1-PDGFB: Fusion'), ('642', 'COL1A1-PDGFB fusion: '), ('653', 'SYT-SSX: fusion'), ('655', 'SS18 (SYT)-SSX : fusion transcripts'), ('682', 'CBL: df'), ('688', 'CALM1: dsf'), ('779', 'new: abb'), ('784', 'new: 1'), ('785', 'new2: 2'), ('786', 'new3: 3'), ('790', 'CALM1: s'), ('805', 'CIC-DUX4 : Fusion test'), ('806', 'CALM1: new'), ('825', 'CIC-DUX4 Fusion: '), ('917', 'CAMLG: s'), ('921', 'ABCB1: e'), ('959', 'TSC2 mutation: '), ('989', 'NF1 mutation: '), ('1022', 'PTEN: Loss '), ('1056', 'TFE3: Intense immunostaining'), ('1118', ' IHC for SATB2, ALK-fusion en ROS1 negative: '), ('1155" selected="selected', 't(4;19)(q35;q13.1) CIC-DUX4 Fusion: ')], max_length=200, null=True),
        ),
    ]
