# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-07 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0010_auto_20170407_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aberration',
            fields=[
                ('crdbbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='casereport.CRDBBase')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('casereport.crdbbase',),
        ),
        migrations.RemoveField(
            model_name='casereport',
            name='aberrations',
        ),
        migrations.AddField(
            model_name='casereport',
            name='aberrations',
            field=models.ManyToManyField(blank=True, to='casereport.Aberration'),
        ),
    ]
