# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-18 19:45
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0012_auto_20170407_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='pathology',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
    ]
