# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0013_auto_20170418_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='authorized_reps',
            field=models.ManyToManyField(blank=True, to='casereport.AuthorizedRep', verbose_name='Alternative Correspondence Email Address'),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='primary_physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_case', to='casereport.Physician', verbose_name='Case Report Author'),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='referring_physician',
            field=models.ManyToManyField(blank=True, to='casereport.Physician', verbose_name='Case Report Co-Authors'),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Case Title'),
        ),
    ]
