# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-24 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0014_auto_20170419_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReportReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='casereport',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casereport', to='casereport.CaseReportReview'),
        ),
    ]
