# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0016_add_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready to Review'), ('approved', 'Approved'), ('changes', 'Need Changes'), ('reviewed', 'Reviewed'), ('edited', 'Edited')], default='draft', max_length=50),
        ),
    ]
