# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0018_add_approval_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='workflow_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('review', 'Review'), ('live', 'Live')], default='draft', help_text='Workflow state', max_length=50),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready to Review'), ('approved', 'Approved'), ('changes', 'Need Changes'), ('reviewed', 'Reviewed'), ('edited', 'Edited')], default='draft', help_text='Old State', max_length=50),
        ),
    ]
