# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-05 15:03
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0019_explicit_workflow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='workflow_state',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('review', 'Review'), ('live', 'Live')], default='draft', help_text='Workflow state', max_length=50),
        ),
    ]
