# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-06 18:10
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0020_FSM_for_casereport_workflow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='workflow_state',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('administrative processing', 'Administrative Processing'), ('author review', 'Author Review'), ('live', 'Live')], default='draft', help_text='Workflow state', max_length=50),
        ),
    ]
