# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0021_casereport_worflow_state_value_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='free_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
