# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0022_add_free_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='casefile_f',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
