# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0024_add_consent_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='date_published',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
