# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-16 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0026_new_and_friendlier_workflow_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='objective_response',
            field=models.CharField(blank=True, choices=[('No Response', 'No Response'), ('Partial Response', 'Partial Response'), ('Disease Progression', 'Disease Progression'), ('Complete Response', 'Complete Response')], max_length=50, null=True),
        ),
    ]
