# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-17 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0027_update_field_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready to Review'), ('approved', 'Approved'), ('changes', 'Need Changes'), ('reviewed', 'Reviewed'), ('edited', 'Edited')], default='draft', help_text='Deprecating', max_length=50),
        ),
    ]
