# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0029_remove_casereport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtypeOption',
            fields=[
                ('crdbbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='casereport.CRDBBase')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('casereport.crdbbase',),
        ),
    ]
