# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-23 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def copy_subtypeobj_data(apps, schema_editor):
    SubtypeOption = apps.get_model("casereport", "SubtypeOption")
    CaseReport = apps.get_model("casereport", "CaseReport")
    for casereport in CaseReport.objects.all():
        if casereport.subtype:
            try:
                obj = SubtypeOption.objects.get(name=casereport.subtype)
                casereport.subtype_obj = obj
                casereport.save()
            except:
                pass


def remove_subtypeobj_data(apps, schema_editor):
    CaseReport = apps.get_model("casereport", "CaseReport")
    for casereport in CaseReport.objects.all():
        casereport.subtype_obj = None


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0031_insert_subtype_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='subtype_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casereport.SubtypeOption'),
        ),
        migrations.RunPython(copy_subtypeobj_data, remove_subtypeobj_data),
    ]
