# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-23 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0032_casereport_subtype_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casereport',
            name='subtype',
        ),
    ]
