# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-23 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0033_remove_casereport_subtype'),
    ]

    operations = [
        migrations.RenameField('CaseReport', 'subtype_obj', 'subtype'),
    ]
