# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-25 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0034_rename_subtypeobj_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='subtype_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
