# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-30 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0035_casereport_subtype_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecularabberation',
            name='molecule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
