# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-26 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0036_0036_aberrations_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecularabberation',
            name='molecule',
        ),
    ]
