# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-09 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# casereport.migrations.0043_shareable

class Migration(migrations.Migration):

    replaces = [('casereport', '0043_shareable'), ('casereport', '0044_add_origin'), ('casereport', '0045_auto_20171218_2000')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('casereport', '0042_auto_20170630_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='shareable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='casereport',
            name='origin_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='casereport',
            name='origin_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
