# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-10 19:58
from __future__ import unicode_literals

from django.db import migrations
from jsonfield_compat.fields import JSONField


class ExternalAppAlterField(migrations.AlterField):
    """ Wraps all calls that reference the app_label with the label
    of the external app.
    """
    def __init__(self, model_name, name, field, preserve_default=True,
                 app_label="actstream"):
        super(ExternalAppAlterField, self).__init__(model_name, name, field,
                                                    preserve_default)
        self._app_label = app_label

    def state_forwards(self, app_label, state):
        return super(ExternalAppAlterField, self).state_forwards(
            self._app_label, state)

    def database_backwards(self, app_label, schema_editor,
                           from_state, to_state):
        return super(ExternalAppAlterField, self).database_backwards(
            self._app_label,
            schema_editor,
            from_state,
            to_state)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        return super(ExternalAppAlterField, self).database_forwards(
            self._app_label,
            schema_editor,
            from_state,
            to_state)

    def references_field(self, model_name, name, app_label=None):
        return super(ExternalAppAlterField, self).references_field(
            model_name,
            name,
            app_label=self._app_label)


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0044_patch_actstream'),
    ]

    operations = [
        ExternalAppAlterField(
            model_name='action',
            name='data',
            field=JSONField(default=False, editable=False, null=True),
            preserve_default=True,
            app_label="actstream",
        ),
    ]
