# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-03-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0046_fix_actstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='aberrations_other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='attachment1_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='attachment2_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='attachment3_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='subtype_other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Case Title'),
        ),
    ]
