# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160114_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='contact',
            field=models.BooleanField(default=False, help_text='If selected, users assigned this role may be treated as the point of contact for their project.'),
        ),
    ]
