# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 22:48
from __future__ import unicode_literals

from django.db import migrations


def set_project_contact_role(apps, schema_editor):
    Role = apps.get_model('projects', 'Role')
    Role.objects.filter(title='Principal Investigator / Contact').update(contact=True)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_role_contact'),
    ]

    operations = [
        migrations.RunPython(set_project_contact_role)
    ]
