# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160320_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bibliography',
        ),
    ]
