# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_bibliography'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_required',
            field=models.BooleanField(default=True, help_text='If checked, registrants must be approved before joining.'),
        ),
    ]
