# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160420_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_opt_in',
            field=models.BooleanField(default=False, help_text='If checked, all members will be automatically added to this project.', verbose_name='Automatically opt-in members'),
        ),
    ]
