# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_auto_opt_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'ordering': ['project']},
        ),
    ]
