# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-28 21:07
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20160519_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='state',
            field=django_fsm.FSMField(choices=[('moderator', 'Moderator'), ('member', 'Member'), ('pending', 'Pending Approval')], default='member', max_length=50),
        ),
    ]
