# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-17 21:40
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20160519_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=django_fsm.FSMField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
