# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-01 18:30
from __future__ import unicode_literals

from django.db import migrations


def preserve_role(apps, schema_editor):
    ProjectMembership = apps.get_model('projects', 'projectmembership')
    for pm in ProjectMembership.objects.all():
        role = pm.role
        if role and role.contact:
            pm.state = 'moderator'
            pm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectmembership_state'),
    ]

    operations = [
        migrations.RunPython(preserve_role),
        migrations.RemoveField(
            model_name='projectmembership',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
