# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-08 15:15
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20170303_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='state',
            field=django_fsm.FSMField(choices=[('moderator', 'Moderator'), ('member', 'Member'), ('pending', 'Applicant')], default='member', max_length=50),
        ),
    ]
