# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-20 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_initial_state_as_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectmembership_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
