# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-24 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_change_membership_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
