# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_project_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='email_prefs',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediately'), ('digest', 'Weekly'), ('never', 'Never')], max_length=20, null=True),
        ),
    ]
