# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projectmembership_email_prefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='email_prefs',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediately'), ('digest', 'Weekly'), ('never', 'Never')], default='digest', max_length=255, null=True, verbose_name='Email notification preferences for Groups'),
        ),
    ]
