# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_add_explcit_digest_prefs_to_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='digest_prefs',
            field=models.CharField(blank=True, choices=[('enabled', 'Email me a weekly digest of all items shared with me and with groups to which I belong.'), ('disabled', 'Do not email me a weekly digest (*). I will check my Dashboard to view shared items')], default='enabled', max_length=255, null=True, verbose_name='Email digest preferences'),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='email_prefs',
            field=models.CharField(blank=True, choices=[('user_and_group', 'Email me immediately when an item is shared with me individually or with groups to which I belong.'), ('disabled', 'Do not send immediate email notifications (*).')], max_length=255, null=True, verbose_name='Email notification preferences for Groups'),
        ),
    ]
