# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-08-31 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_reset_default_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='email_prefs',
            field=models.CharField(blank=True, choices=[('user_and_group', 'Email me immediately when an item is shared with me individually or with groups to which I belong.'), ('disabled', 'Do not send immediate email notifications.*')], max_length=255, null=True, verbose_name='Email notification preferences for Groups'),
        ),
    ]
