# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-27 20:53
from __future__ import unicode_literals

from django.db import migrations

INITIAL_TAGS = """
    aldoxorubicin
    dactinomycin
    dacarbazine
    docetaxel
    doxorubicin
    eribulin
    gemcitabine
    ifosfamide
    imatinib
    ipilimumab
    nivolumab
    olaratumab
    pazopanib
    pembrolizumab
    regorafenib
    sirolimus
    sitravatinib
    sunitinib
    trabectedin
    vincristine
    immunotherapy
    radiotherapy
    adjuvant
    neoadjuvant
    chemotherapy
    chemoradiotherapy
    metastatic
    palliative
    surgery
    preventative
    precancer
"""

def load_tags(apps, schema_editor):
    tag_words = [tw for tw in map(str.strip, INITIAL_TAGS.split()) if tw]
    from taggit.models import Tag
    print("creating tags")
    for word in tag_words:
        tag, is_new = Tag.objects.get_or_create( name=word, slug=word )
        if is_new:
            print( tag )

class Migration(migrations.Migration):

    dependencies = [
        ('managedtags', '0001_initial'),
    ]

    operations = [
        migrations.RunPython( load_tags )
    ]
