# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-27 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedtags', '0002_auto_20170627_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedtag',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='managedtag',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
