# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-28 16:11
from __future__ import unicode_literals
from django.db import migrations

SUPPORTED_TAGS = """
    aldoxorubicin
    dactinomycin
    dacarbazine
    docetaxel
    doxorubicin
    eribulin
    gemcitabine
    ifosfamide
    imatinib
    ipilimumab
    nivolumab
    olaratumab
    pazopanib
    pembrolizumab
    regorafenib
    sirolimus
    sitravatinib
    sunitinib
    trabectedin
    vincristine
    immunotherapy
    radiotherapy
    adjuvant
    neoadjuvant
    chemotherapy
    chemoradiotherapy
    metastatic
    palliative
    surgery
    preventative
    precancer
"""


def deprecate_unsupported_tags(apps, schema_editor):
    tag_words = [tw for tw in map(str.strip, SUPPORTED_TAGS.split()) if tw]
    from taggit.models import Tag

    for tag in Tag.objects.all():
        if tag.slug not in tag_words:
            print("deprecating", tag)
            tag.delete()

    print("surviving tags:")
    for t in Tag.objects.all():
        print(t)


class Migration(migrations.Migration):

    dependencies = [
        ('managedtags', '0003_auto_20170627_2109'),
    ]

    operations = [
        migrations.RunPython(deprecate_unsupported_tags)
    ]
