# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_urlconfrevision'),
        ('newsfeed', '0002_newsitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeedpluginconfiguration',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='NewsfeedPluginConfiguration',
        ),
    ]
