# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
