# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20161011_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookmarks.Folder'),
        ),
    ]
