# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.TextField(verbose_name='project/user ID')),
                ('target_id', models.TextField(verbose_name='target ID')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_type_set_for_sharedcontent', to='contenttypes.ContentType', verbose_name='target content type')),
                ('viewer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_type_set_for_sharedcontent', to='contenttypes.ContentType', verbose_name='viewer content type')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sharedcontent',
            unique_together=set([('target_id', 'target_type'), ('viewer_id', 'viewer_type')]),
        ),
    ]
