# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 02:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectreference',
            options={'verbose_name': 'Reference'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Raw Reference'},
        ),
        migrations.AddField(
            model_name='reference',
            name='parsed_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pubmed_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
