# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

from rlp.bibliography import choices
from rlp.bibliography.models import parse_crossref_data, parse_pubmed_data


def populate_parsed_data(apps, schema_editor):
    from Bio import Entrez
    Reference = apps.get_model('bibliography', 'Reference')
    for ref in Reference.objects.filter(source=choices.CROSSREF):
        ref.parsed_data = parse_crossref_data(ref.raw_data)
        ref.save()
    pmids = Reference.objects.filter(source=choices.PUBMED).values_list('pubmed_id', flat=True)
    if not pmids:
        return
    Entrez.email = settings.PUBMED_EMAIL
    results = Entrez.read(
        Entrez.efetch(db='pubmed', retmode='xml', id=','.join(pmids))
    )
    for result in results:
        pubmed_id = [str(r) for r in result['PubmedData']['ArticleIdList'] if r.attributes['IdType'] == 'pubmed'][0]
        ref = Reference.objects.get(source=choices.PUBMED, pubmed_id=pubmed_id)
        ref.parsed_data = parse_pubmed_data(result)
        ref.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0002_auto_20160323_0229'),
    ]

    operations = [
        migrations.RunPython(populate_parsed_data)
    ]
