# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0004_auto_20160607_1619'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set([('reference', 'author')]),
        ),
    ]
