# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 19:08
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('bibliography', '0005_auto_20160719_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreference',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
