# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0006_projectreference_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='upload',
            field=models.FileField(blank=True, max_length=255, upload_to='references', verbose_name='Upload file'),
        ),
    ]
