# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0014_auto_20160519_1731'),
        ('bibliography', '0007_reference_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project')),
                ('recipients', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.Reference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_references', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
