# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-22 15:42
from __future__ import unicode_literals

from django.db import migrations


def share_with_project(apps, schema_editor):
    ProjectReference = apps.get_model('bibliography', 'projectreference')
    SharedContent = apps.get_model('core', 'sharedcontent')
    ContentType = apps.get_model('contenttypes', 'contenttype')
    for projref in ProjectReference.objects.all():
        # GenericForeignKey doesn't work here, so do it manually
        SharedContent.objects.create(
            viewer_type=ContentType.objects.get_for_model(projref.project),
            viewer_id=projref.project.id,
            target_type=ContentType.objects.get_for_model(projref),
            target_id=projref.id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0008_referenceshare'),
    ]

    operations = [
        migrations.RunPython(share_with_project),
        migrations.RemoveField(
            model_name='projectreference',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='project',
        ),
    ]
