# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-03 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0009_remove_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
