# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-04 19:53
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


'''allow sharing, tagging, discussions on Reference objects'''


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('bibliography', '0010_reference_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='tags',
            field=taggit.managers.TaggableManager(
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags',
            ),
        ),
    ]
