# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-24 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0013_drop_projectreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
