# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-27 20:52
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0015_switch_to_managedtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='mtags',
            field=taggit.managers.TaggableManager(help_text='A Comma separated list of UNAPPROVED tags.', through='managedtags.TaggedByManagedTag', to='managedtags.ManagedTag', verbose_name='Tags'),
        ),
    ]
