# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-09 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from ..models import UserReference

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# rlp.bibliography.migrations.0020_shareable


def set_shareable(apps, schema_editor):
    """set the shareable flag on existing content
       it should be false if only shared with a closed group
    """
    for obj in UserReference.objects.all():
        closed = []
        for viewer in obj.get_viewers():
            if not hasattr(viewer, 'approval_required'):
                continue
            closed.append(viewer.approval_required)
        if closed and all(closed):
            obj.shareable = False
            obj.save()

class Migration(migrations.Migration):

    replaces = [('bibliography', '0020_shareable'), ('bibliography', '0021_add_origin'), ('bibliography', '0022_auto_20171218_2000')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bibliography', '0019_auto_20170706_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='origin_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='reference',
            name='origin_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='reference',
            name='shareable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='userreference',
            name='shareable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='userreference',
            name='origin_id',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='userreference',
            name='origin_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        # migrations.RunPython(
        #     code=set_shareable,
        # ),
    ]
