# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='upload',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='upload',
        ),
    ]
