# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20160216_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='working_document',
            field=models.BooleanField(default=False, verbose_name='Core Project Document (will appear as top-listed document)'),
        ),
    ]
