# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20160217_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
    ]
