# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-15 16:19
from __future__ import unicode_literals

from django.db import migrations


def share_with_project(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    SharedContent = apps.get_model('core', 'sharedcontent')
    ContentType = apps.get_model('contenttypes', 'contenttype')
    for doc in Document.objects.all():
        # GenericForeignKey doesn't work here, so do it manually
        SharedContent.objects.create(
            viewer_type=ContentType.objects.get_for_model(doc.project),
            viewer_id=doc.project.id,
            target_type=ContentType.objects.get_for_model(doc),
            target_id=doc.id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_tags'),
    ]

    operations = [
        migrations.RunPython(share_with_project),
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
    ]
