# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_remove_document_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='working_document',
        ),
        migrations.AddField(
            model_name='document',
            name='copyright',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='share_link',
            field=embed_video.fields.EmbedVideoField(help_text='YouTube URL'),
        ),
    ]
