# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-25 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_shareable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(max_length=250, upload_to='docs/%Y/%m/%d'),
        ),
    ]
