# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_longerfilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
